spring:
  application:
    name: booking-service
  datasource:
    url: jdbc:h2:mem:borrowingDB
    driver-class-name: org.h2.Driver
    username: sa
    password:
    h2:
      console:
        enabled: true
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  instance:
    preferIpAddress: true