server:
  port: 8084

spring:
  application:
    name: customer-service

management:
  endpoints:
    web:
      exposure:
        include: "*"
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${DISCOVERY_SERVICE_URL:http://localhost:8761/eureka}

  instance:
    preferIpAddress: true